"""empty message

Revision ID: a5a2a33f15f8
Revises: a604b46bc062
Create Date: 2022-04-06 23:39:56.455909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a2a33f15f8'
down_revision = 'a604b46bc062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_cart_productID_fkey', 'order_cart', type_='foreignkey')
    op.drop_column('order_cart', 'productID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_cart', sa.Column('productID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_cart_productID_fkey', 'order_cart', 'product', ['productID'], ['productID'])
    # ### end Alembic commands ###
