"""empty message

Revision ID: ee07ae21321e
Revises: b52990911d0d
Create Date: 2022-04-07 01:12:17.912070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee07ae21321e'
down_revision = 'b52990911d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
    # ### end Alembic commands ###
